#!/usr/bin/env bash
# The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]
# Display information about subdomains.

domain_info () {
	dig "$2"."$1" | awk '/ANSWER SECTION:/ {getline; print}' | 
	awk -v subdomain="$2" '{ print "The subdomain " subdomain " is a " $4 " record and points to " $5}'
}

if [ "$#" == 1 ]
then
  domain_info "$1" "www"
  domain_info "$1" "lb-01"
  domain_info "$1" "web-01"
  domain_info "$1" "web-02"
elif [ "$#" == 2 ]
then
  domain_info "$1" "$2"
fi
