#!/usr/bin/env bash
#  Install nginx web server
# Update package list
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create a basic HTML file with Hello World content
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
# Configure Nginx to listen on port 80
sudo bash -c 'echo "server {
    listen 80;
    server_name _;
    location / {
        root /var/www/html;
        index index.html;
    }
}" > /etc/nginx/sites-available/default'

# Restart Nginx
sudo service nginx restart
