#!/usr/bin/env bash
# Installs nginx, configures index.html, 404 error and 301 redirect
# Also inserts custom header in /etc/nginx/sites-available/default

var=$(hostname)
string="error_page 404 \/custom_404.html;\n location \/redirect_me {\n return 301 \$scheme:\/\/www.google.com;"
string2="server {\n\tadd_header X-Served-By $var;"

apt-get update -y
apt-get install nginx -y
echo "Hello World!" > /usr/share/nginx/html/index.html
mkdir -p /var/www/html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

sudo sed -i -E "/^location \/ {/s|.*|$string|" /etc/nginx/sites-available/default
sudo sed -i -E "/^server {/s|.*|$string2|" /etc/nginx/sites-available/default
sudo service nginx start
