#!/usr/bin/env bash
# Installs nginx, configures index.html, 404 error and 301 redirect
# Also inserts custom header in /etc/nginx/sites-available/default

apt-get update -y
apt-get install nginx -y

mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
touch /var/www/html/404-error.html
echo "Ceci n'est pas une page" > /var/www/html/404-error.html

printf %s "server {
	listen		80 default_server;
	listen 		[::]:80 default_server;
	add_header 	X-Served-By $HOSTNAME
	root		/var/www/html;
	index		index.html index.htm;

	location /redirect_me {
		return 301 http://google.com/;
	}

	error_page 404 /404-error.html;
	location /404 {
		root /var/www/html;
		internal;
	}
}" > /etc/nginx/sites-available/default

service nginx restart
