#!/usr/bin/env bash

# Set MySQL root password from command line argument
MYSQL_ROOT_PASSWORD="$1"

# Define the file names
MYSQL_DUMP_FILE="backup.sql"

# Dump all MySQL databases into a single file
mysqldump -u root -p"$MYSQL_ROOT_PASSWORD" --all-databases > "$MYSQL_DUMP_FILE"

# Compress the dump file into a tar.gz archive
tar -czvf "$(date +%d-%m-%Y)".tar.gz "$MYSQL_DUMP_FILE"
