#!/usr/bin/env bash
# bash script that displays numbers from 1 to 100

i=1
while [ $i -lt 101 ]
do
 if [ $((i % 5)) -eq 0 ] && [ $((i % 3)) -eq 0 ]
  then
   echo "FizzBuzz"
 elif [ $((i % 3)) -eq 0 ]
  then
   echo "Fizz"
 elif [ $((i % 5)) -eq 0 ]
  then
   echo "Buzz"
 else
  echo "$i"
 fi
 ((i++))
done
