#!/usr/bin/env bash
# bash script that displays "Best School" 10 times
i=0
while [ $i -lt 10 ]
do
 if [ $i -eq 8 ]
  then
   echo "Best School"
   echo "Hi"
 else
  echo "Best School"
 fi
 ((i++))
done
