#!/usr/bin/env bash
# a Bash script that displays the time for 12 hours and 59 minutes:

h=0
m=1
while [ $h -le 12 ]
do
	m=1 #resetting minutes
	echo "Hour: $h"
	while [ $m -lt 60 ]
	do
		echo "$m"
		((m++))
	done
	((h++))
done
