#!/usr/bin/env bash
# a Bash script that configures an Ubuntu server with the below requirements.
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.
cp /etc/hosts ~/host_file
sed -i s/127.0.0.1/127.0.0.2/ ~/host_file
echo '8.8.8.8  facebook.com' >> ~/host_file
cp -f ~/host_file /etc/hosts

